version: '3.8'
services:
  postgres-b:
    container_name: postgre-main
    image: postgres:15.1
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgre_db:/var/lib/postgresql/data
    networks:
      - pg-sharding
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:6.16
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}
    ports:
      - "5050:80"
    networks:
      - pg-sharding

  postgres-b1:
    container_name: postgre-shard-1
    image: postgres:15.1
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    volumes:
      - postgre_b1_db:/var/lib/postgresql/data
    networks:
      - pg-sharding
    restart: unless-stopped

  postgres-b2:
    container_name: postgre-shard-2
    image: postgres:15.1
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5434:5432"
    volumes:
      - postgre_b2_db:/var/lib/postgresql/data
    networks:
      - pg-sharding
    restart: unless-stopped

volumes:
  postgre_db: {}
  postgre_b1_db: {}
  postgre_b2_db: {}

networks:
  pg-sharding:
    driver: bridge
